### ISSUE TITLE
Attachment

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-fixtures#13]
## Add file to media

```yaml
WP_Post:
  the_att:
    type: attachment
    meta_input:
      _wp_attached_file: <image()>
```

could be simplified to

```yaml
attachment: # or media:
  the_att:
    file: <image()>
```

Mock:

* thumbnail_id will be 0 until persisted

Persistence:

* Forces the file in no matter if the file type is allowed or not

## Attach such media to entities

```yaml
WP_Post:
  post_with_att:
    type: foo
    meta_input:
      _thumbnail_id: "@the_att"
```

could become

```yaml
WP_Post:
  post_with_att:
    type: foo
    thumbnail: "@the_att"
```

## Provider

May need ...

* `<wp_upload_dir($time)>` which returns `wp_upload_dir($time)['path']` by default
* `<wp_max_upload_size()>` to create files which are exactly this big or slightly bigger/smaller for testing purposes
* `<wp_get_mime_types()>` and `<wp_get_mime_type()>` to randomly select one
* `<get_allowed_mime_types($unfiltered = false)>` and `<get_allowed_mime_type()>` to randomly select one
* `<get_intermediate_image_sizes('thumbnail')>, <get_intermediate_image_size()>, get_intermediate_image_width('thumbnail') and get_intermediate_image_height(...)` to randomly select one
