### ISSUE TITLE
user: Automagically make key the user_login

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-fixtures#16]
A configuration like

```yaml
_defaults:
  WP_User:
    user_login: %key%

WP_User:
  foo:
    user_pass: bar
```

Should create a user with the user_login "foo" until defined otherwise.
This or wp-fixtures needs a config file.
