### ISSUE TITLE
Post metadata hydration doesn't work

### ISSUE THREAD

**Issue by ju1ius** [rmp-up/wp-fixtures#17]
Hi,

The sample fixture you provide fails to hydrate post metadata:

```yaml
# /path/to/posts.yaml
WP_Post:
  page_1:
    # Well known wp_insert_post() structure
    post_type: page
    post_title: Imprint
    post_content: |
      Beth Doe
      Meestreet 42
      1337 Muskegon
    meta_input:
      simple: 1
      flat: # will append like add_post_meta
        - penny
        - claire
        - emily
        - lucy
      complex: # will be serialized
        company: True TV
        best: Ellen
```

```
$ wp-cli fixture config/fixtures/posts.yaml
Error: An error occurred while generating the fixture "page_1" (WP_Post): Could not hydrate the property "meta_input" of the object "page_1" (class: WP_Post).
```
