### ISSUE TITLE
Random user

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-fixtures#4]
Instead of writing:

```yaml
\RmpUp\WordPress\Fixtures\Entity\WooCommerce\Order:
  order_1:
    user: "@user_1"

\RmpUp\WordPress\Fixtures\Entity\User:
  user_1:
    email: some_random_person@example.org
```

we just want to write:

```yaml
\RmpUp\WordPress\Fixtures\Entity\WooCommerce\Order:
  order_1:
    user: "<@wpUser()>"
```

or even less:

```yaml
\RmpUp\WordPress\Fixtures\Entity\WooCommerce\Order:
  order_1: ~
```

which notices the missing mandatory data and creates a random one. This spares some time and clutter.

---

Technically write a proper extension to Faker.
