### ISSUE TITLE
Random post

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-fixtures#5]
As a developer instead of 

```
Comment:
  post: '@some_post'

Post:
  some_post: ~
```

I want to write

```
Comment:
  post: '<wpPost("the_post_type")>'
```

when I don't care about the post itself.
