### ISSUE TITLE
Random comments

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-fixtures#6]
Instead of 

```
Post:
  foo: ~
  meta_input:
    bar: '@c1.ID'

Comments:
  c1:
    post: '@foo'
```

I want to write:

```
Post:
  foo: ~
  meta_input:
    bar: '<wpComment()>.id'
```

---

Hint: Check for case-sensitive "ID" and "id"
